### ISSUE TITLE
Documentation versions differ to latest or selected

### ISSUE THREAD

**Issue by fty4** [argoproj-labs/argocd-vault-plugin#396] opened 2022-08-31 12:41 UTC
**Describe the bug**
The documentation (e.g. [`v1.12.0`](https://github.com/argoproj-labs/argocd-vault-plugin/blob/v1.12.0/docs/installation.md)) uses `AVP_VERSION` in different version as [selected](https://argocd-vault-plugin.readthedocs.io/en/v1.12.0/installation/) or [latest](https://argocd-vault-plugin.readthedocs.io/en/latest/).

**To Reproduce**
See examples from [`v1.12.0`](https://github.com/argoproj-labs/argocd-vault-plugin/blob/v1.12.0/docs/installation.md):

https://github.com/argoproj-labs/argocd-vault-plugin/blob/9c7288a5b2d395fea19c1100f2cd07b547cc1ee2/docs/installation.md?plain=1#L82-L83

https://github.com/argoproj-labs/argocd-vault-plugin/blob/9c7288a5b2d395fea19c1100f2cd07b547cc1ee2/docs/installation.md?plain=1#L118

https://github.com/argoproj-labs/argocd-vault-plugin/blob/9c7288a5b2d395fea19c1100f2cd07b547cc1ee2/docs/installation.md?plain=1#L192-L193

https://github.com/argoproj-labs/argocd-vault-plugin/blob/9c7288a5b2d395fea19c1100f2cd07b547cc1ee2/docs/installation.md?plain=1#L277

**Expected behavior**
The selected version here e.g. `1.12.0` should be displayed.

**Comment by werne2j** [comment] 2022-10-26 16:02
Closing this as a duplicate of #410

**Closed by werne2j** 2022-10-26 16:02 UTC
