### ISSUE TITLE
Getting * namespace not authorized when using with k8s auth 

### ISSUE THREAD

**Issue by Shapai** [argoproj-labs/argocd-vault-plugin#343] opened 2022-05-13 07:53 UTC
I have been trying to use the kubernetes auth along with AVP plugin 

i have been using the repo 
https://github.com/jkayani/avp-demo-kubecon-2021 to test AVP plugin as demonstrated in kubecon2021 video

have created a secret and passed it to repo server deployment as below 

```
kubectl get secret argocd-vault-plugin-credentials -n argocd -o yaml
apiVersion: v1
data:
  AVP_AUTH_TYPE: ***
  AVP_K8S_ROLE: argocd
  AVP_TYPE: ****
  VAULT_ADDR: ****
kind: Secret
metadata:
  creationTimestamp: "2022-05-12T16:43:30Z"
  name: argocd-vault-plugin-credentials
  namespace: argocd
  resourceVersion: "16553"
  uid: 03bb80c8-4884-4b19-8e5a-5f75f88466bc
type: Opaque
```

i have created the secret in vault as below 

```
$ vault secrets enable -version=2 -path="secret" kv
Success! Enabled the kv secrets engine at: secret/
/ $ vault kv put secret/my-nginx password="secret-password"
Key              Value
---              -----
created_time     2022-05-12T16:29:38.720640596Z
deletion_time    n/a
destroyed        false
version          1
/ $ vault kv get secret/my-nginx
====== Metadata ======
Key              Value
---              -----
created_time     2022-05-12T16:29:38.720640596Z
deletion_time    n/a
destroyed        false
version          1

====== Data ======
Key         Value
---         -----
password    secret-password
```

then created policy 

```
/ $  vault policy read demo-policy
path "secret/*" {
  capabilities = ["read"]
}

```

attached the policy to role `argocd`

```
vault read  auth/kubernetes/role/argocd
Key                                 Value
---                                 -----
bound_service_account_names         [default]
bound_service_account_namespaces    [default]
policies                            [demo-policy]
token_bound_cidrs                   []
token_explicit_max_ttl              0s
token_max_ttl                       0s
token_no_default_policy             false
token_num_uses                      0
token_period                        0s
token_policies                      [demo-policy]
token_ttl                           0s
token_type                          default
```

but when i try to create the application it complains with below error message 

`level=error msg="finished unary call with code Unknown" error="`argocd-vault-plugin generate ./` failed exit status 1: Error: Error making API request.\n\nURL: PUT http://10.43.192.188:8200/v1/auth/kubernetes/login\nCode: 500. Errors:\n\n* namespace not authorized`

I also tried making a request from a pod in default namespace to Vault to validate

```
OCP_TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
/ $ wget --no-check-certificate -q -O- --post-data '{"jwt": "'"$OCP_TOKEN"'", "role": "argocd"}' http://vault:8200/v1/auth/kubernetes/login
{"request_id":"0b908997-86a7-1792-fc8c-cc0607b78e86","lease_id":"","renewable":false,"lease_duration":0,"data":null,"wrap_info":null,"warnings":null,"auth":{"client_token":"s.GOdlO7RPV2g8Wi4wFr5VKOMO","accessor":"rLuzki8RnWIkiYia5eOsxxll","policies":["default","demo-policy"],"token_policies":["default","demo-policy"],"metadata":{"role":"argocd","service_account_name":"default","service_account_namespace":"default","service_account_secret_name":"","service_account_uid":"e0f31874-905e-49f9-b7c5-fd19939a31da"},"lease_duration":2764800,"renewable":true,"entity_id":"7a086939-b32f-bbad-2feb-f158d94afa36","token_type":"service","orphan":true}}
```
**Screenshots**
![image](https://user-images.githubusercontent.com/101193213/168236223-de3c8d43-54a1-4149-b37f-472dadb8f0d3.png)

the ui where i am passing the git repo and path 
![image](https://user-images.githubusercontent.com/101193213/168237128-e62c26bb-94fe-46fe-bdc8-650aa1b7233b.png)

**Additional context**

argocd vault plugin 

```
argocd-vault-plugin version
argocd-vault-plugin v1.6.0 (947668d260d7e630b3dbc7d9dadfc4ed0650ccd3) BuildDate: 2021-12-01T21:37:22Z
```

**Comment by werne2j** [comment] 2022-05-13 13:00
@jkayani May correct me if i am wrong but that repo/example is using the `default` namespace, where as you have deployed everything in the `argocd` namespace.

```
bound_service_account_names         [default]
bound_service_account_namespaces    [default]
```
should be `argocd` i believe.

**Comment by Shapai** [comment] 2022-05-13 13:23
Hey @werne2j thanks, i am deploying the application in default namespace as described in the repo, so the pods in default ns should be able to get the secret, i have created the policy named argocd as described in the vault [yaml](https://github.com/jkayani/avp-demo-kubecon-2021/blob/main/vault/app.yaml) of this repo 

```
This is how i have created the role 
/ $ vault write auth/kubernetes/role/argocd \
>         bound_service_account_names=default \
>         bound_service_account_namespaces=default \
>         policies=demo-policy
```
![image](https://user-images.githubusercontent.com/101193213/168293231-83cee0bc-8eae-4dfa-b697-e540f8923d10.png)

**Comment by Shapai** [comment] 2022-05-13 13:40
all the workloads of argo are in argocd namespace, so the secret is also deployed in argocd ns

```
kubectl get pods -n argocd
NAME                                             READY   STATUS    RESTARTS        AGE
argocd-redis-7df774d774-lrwfs                    1/1     Running   1 (6h53m ago)   19h
argocd-application-controller-6b6845f994-zvqph   1/1     Running   1 (6h53m ago)   19h
argocd-server-5789587bcc-xjj7g                   1/1     Running   1 (6h53m ago)   19h
argocd-dex-server-c87775f74-r2wdf                1/1     Running   1 (6h53m ago)   19h
argocd-repo-server-7d45657f5c-z79pc              1/1     Running   0               6h32m
```
the repo server pod has all the AVP creds available that are passed through secret 

```
 printenv | grep AVP
AVP_TYPE=vault
AVP_AUTH_TYPE=k8s
AVP_K8S_ROLE=argocd
```

**Comment by Shapai** [comment] 2022-05-13 14:30
@werne2j , so is it that argocd workloads should also be in default ns ? So i have vault and the application that will be deployed in default ns and argocd role are bound the default ns and sa . 
How can this be solved if i have argocd in argocd ns and want to deploy app in some other ns ?
For ex default in this case ?

**Comment by jkayani** [comment] 2022-06-02 05:01
Hi,

I think there's some confusion here. Jake is right, the below snippet:

```
vault read  auth/kubernetes/role/argocd
Key                                 Value
---                                 -----
bound_service_account_names         [default]
bound_service_account_namespaces    [default]
```
means only pods using the `default` SA from the `default` namespace can talk to Vault with the `argocd` Vault role. Your workloads that use the secrets, being deployed via ArgoCD + AVP, can be in any namespace (in any cluster) - that's not relevant here. 

> How can this be solved if i have argocd in argocd ns and want to deploy app in some other ns ?

To do this, amend the `argocd` Vault role so that it's granted to the `default` SA (or whichever SA the `argocd-repo-server` uses) in the `argocd` namespace. Then, create Argo app manifests that specify the desired destination namespace. The end result should be that AVP is able to talk to Vault, since it's SA + namespace are allowed to use the Vault role, the YAML templates are successfully replaced, and the ArgoCD applies them all to the desired destination namespace.

**Comment by jkayani** [comment] 2022-06-12 22:55
Closing this issue since this use case is confirmed to work. Here's an example: https://github.com/jkayani/avp-demo-kubecon-2021/blob/sidecar/vault/app.yaml#L39

**Closed by jkayani** 2022-06-12 22:55 UTC
