### ISSUE TITLE
argocd-vault-plugin with vault using helm charts

### ISSUE THREAD

**Issue by dhinakar2707** [argoproj-labs/argocd-vault-plugin#465] opened 2023-02-17 22:04 UTC
**Is your feature request related to a problem? Please describe.**
I'm using sidecar approach to install argocd-vault-plugin. And also I'm using helm dependency style charts for deploying services in kubernetes cluster. 

<img width="711" alt="image" src="https://user-images.githubusercontent.com/45903612/219801599-f4e5371f-e9d5-428a-aa01-11e240f20033.png">

And I'm trying to define the sensitive values from values.yaml file like below.

<img width="619" alt="image" src="https://user-images.githubusercontent.com/45903612/219801734-be687337-ccdb-40ff-968c-60968ca6e8ef.png">

Please can you help me what all additional changes to be done in configMap and argo-repo-server and in my application manifest.

I'm trying to fetch the secret values directly from vault using values.yaml file. Also I was checking older issues and I'm not able to access the ibm github repo for reference.

**Describe the solution you'd like**

I want to have the placeholder inside the values.yaml file 

auth:
  postgresPassword: <path:secrets/aop/data/application#postgresPassword>
  username: <path:secrets/aop/data/application#username>
  password: <path:secrets/aop/data/application#password>
  database: <path:secrets/aop/data/application#database>

Which the password has to be fetch from vault. Please can someone suggest or guide me on this.

**Comment by werne2j** [comment] 2023-03-07 14:16
Duplicate of https://github.com/argoproj-labs/argocd-vault-plugin/issues/464

**Closed by werne2j** 2023-03-07 14:16 UTC
