### ISSUE TITLE
A simple in the document is incorrect.

### ISSUE THREAD

**Issue by lixiaomei-git** [argoproj-labs/argocd-vault-plugin#391] opened 2022-08-25 08:23 UTC
[https://argocd-vault-plugin.readthedocs.io/en/stable/usage/#with-additional-helm-arguments](https://argocd-vault-plugin.readthedocs.io/en/stable/usage/#with-additional-helm-arguments
)
For argocd-cm ConfigMap configured plugins:
The generate args is `["helm template $ARGOCD_APP_NAME ${helm_args} . --install-crds | argocd-vault-plugin generate -"]`
For sidecar configured plugins:
The generate args is `
helm template $ARGOCD_APP_NAME --install-crds -n $ARGOCD_APP_NAMESPACE ${ARGOCD_ENV_HELM_ARGS} . |
            argocd-vault-plugin generate -
`
We can see the difference between these two simples, the second one using the prefix `ARGOCD_ENV`. In the fact, for argocd 2.4.0, the first one also need to use prefix `ARGOCD_ENV`. It's better to keep these two simples consistent, otherwise it will be very confusing.

**Comment by timofey-drozhzhin** [comment] 2022-09-08 01:48
Seems duplicate of https://github.com/argoproj-labs/argocd-vault-plugin/issues/359

**Comment by vinayan3** [comment] 2022-11-21 23:20
This has been updated in https://github.com/argoproj-labs/argocd-vault-plugin/pull/384/files

**Comment by werne2j** [comment] 2023-03-21 19:54
Closing this as the helm docs have been updated here https://github.com/argoproj-labs/argocd-vault-plugin/pull/431

**Closed by werne2j** 2023-03-21 19:54 UTC
